# Generated by Django 5.0.6 on 2024-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='description',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
