# Generated by Django 5.0.6 on 2024-05-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_diseases_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticCrossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=30)),
                ('name_2', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
